# ============================================================================
# 颜色定义
# ============================================================================
if(NOT DEFINED Color_Reset)
    if(NOT WIN32 OR CMAKE_COLOR_MAKEFILE)
	string(ASCII 27 Esc)
	set(Color_Reset   "${Esc}[0m")
	set(Color_Bold    "${Esc}[1m")
	set(Color_Gray    "${Esc}[90m")
	set(Color_Red     "${Esc}[31m")
	set(Color_Green   "${Esc}[32m")
	set(Color_Yellow  "${Esc}[33m")
	set(Color_Blue    "${Esc}[34m")
	set(Color_Magenta "${Esc}[35m")
	set(Color_Cyan    "${Esc}[36m")
    else()
	set(Color_Reset   "")
	set(Color_Bold    "")
	set(Color_Gray    "")
	set(Color_Red     "")
	set(Color_Green   "")
	set(Color_Yellow  "")
	set(Color_Blue    "")
	set(Color_Magenta "")
	set(Color_Cyan    "")
    endif()
endif()

# ============================================================================
# 增强版检查函数（包装原有检查函数，添加颜色输出）
# ============================================================================

function(enhanced_check_library_exists LIBRARY FUNCTION LOCATION VARIABLE)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} 库: ${LIBRARY} (函数: ${FUNCTION})")
    check_library_exists("${LIBRARY}" "${FUNCTION}" "${LOCATION}" "${VARIABLE}")
    if(${VARIABLE})
	message(STATUS "${Color_Green}[找到]${Color_Reset} 库 ${LIBRARY}")
    else()
	message(STATUS "${Color_Red}[未找到]${Color_Reset} 库 ${LIBRARY}")
    endif()
endfunction()

function(enhanced_check_include_file_cxx HEADER VARIABLE)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} 头文件: ${HEADER}")
    check_include_file_cxx("${HEADER}" "${VARIABLE}")
    if(${VARIABLE})
	message(STATUS "${Color_Green}[找到]${Color_Reset} ${HEADER}")
    else()
	message(STATUS "${Color_Red}[未找到]${Color_Reset} ${HEADER}")
    endif()
endfunction()

function(enhanced_check_function_exists FUNCTION VARIABLE)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} 函数: ${FUNCTION}()")
    check_function_exists("${FUNCTION}" "${VARIABLE}")
    if(${VARIABLE})
	message(STATUS "${Color_Green}[找到]${Color_Reset} ${FUNCTION}()")
    else()
	message(STATUS "${Color_Red}[未找到]${Color_Reset} ${FUNCTION}()")
    endif()
endfunction()

# ============================================================================
# 主逻辑配置（恢复原始逻辑）
# ============================================================================

message(STATUS "${Color_Magenta}[=== 初始化配置 ===]${Color_Reset}")

# 设置 CMake 模块路径
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/Modules)

# 包含使用的模块
message(STATUS "${Color_Gray}[配置]${Color_Reset} 加载 CMake 模块...")
include(DefineInstallationPaths)
include(CheckIncludeFileCXX)
include(CheckFunctionExists)
include(CheckSymbolExists)
include(CheckLibraryExists)
include(CheckCXXCompilerFlag)
include(CheckMkdirArgs)
include(CheckIncludeFiles)

# 设置简短的变量路径名称
message(STATUS "${Color_Gray}[配置]${Color_Reset} 设置安装路径变量")
set(BINDIR ${BIN_INSTALL_DIR})
set(SBINDIR ${SBIN_INSTALL_DIR})
set(SYSCONFDIR ${SYSCONF_INSTALL_DIR})
set(LOCALSTATEDIR ${LOCALSTATE_INSTALL_DIR})
set(MANDIR ${MAN_INSTALL_DIR})

# 设置默认的硬编码配置文件路径
if(WIN32)
    message(STATUS "${Color_Gray}[配置]${Color_Reset} 设置 Windows 配置文件路径")
    set(BNETD_DEFAULT_CONF_FILE "conf/bnetd.conf")
    set(D2CS_DEFAULT_CONF_FILE "conf/d2cs.conf")
    set(D2DBS_DEFAULT_CONF_FILE "conf/d2dbs.conf")
else(WIN32)
    message(STATUS "${Color_Gray}[配置]${Color_Reset} 设置 Unix 配置文件路径")
    set(BNETD_DEFAULT_CONF_FILE "${SYSCONFDIR}/bnetd.conf")
    set(D2CS_DEFAULT_CONF_FILE "${SYSCONFDIR}/d2cs.conf")
    set(D2DBS_DEFAULT_CONF_FILE "${SYSCONFDIR}/d2dbs.conf")
endif(WIN32)

message(STATUS "${Color_Magenta}[=== 外部依赖库检查 ===]${Color_Reset}")

# 库检查 (严格按照原逻辑使用 REQUIRED)
if(WITH_BNETD)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} ZLIB 库...")
    find_package(ZLIB REQUIRED)
    if(ZLIB_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} ZLIB: ${ZLIB_VERSION_STRING}")
    endif()
endif(WITH_BNETD)

if(WITH_LUA)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} Lua 库...")
    find_package(Lua REQUIRED)
    if(Lua_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} Lua: ${LUA_VERSION_STRING}")
    endif()
endif(WITH_LUA)

# 存储模块检查
if(WITH_ODBC)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} ODBC 库...")
    find_package(ODBC REQUIRED)
    if(ODBC_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} ODBC")
    endif()
endif(WITH_ODBC)

if(WITH_MYSQL)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} MySQL 库...")
    find_package(MySQL REQUIRED)
    if(MySQL_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} MySQL")
    endif()
endif(WITH_MYSQL)

if(WITH_SQLITE3)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} SQLite3 库...")
    find_package(SQLite3 REQUIRED)
    if(SQLite3_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} SQLite3: ${SQLite3_VERSION}")
    endif()
endif(WITH_SQLITE3)

if(WITH_PGSQL)
    message(STATUS "${Color_Gray}[检查]${Color_Reset} PostgreSQL 库...")
    find_package(PostgreSQL REQUIRED)
    if(PostgreSQL_FOUND)
	message(STATUS "${Color_Green}[找到]${Color_Reset} PostgreSQL: ${PostgreSQL_VERSION_STRING}")
    endif()
endif(WITH_PGSQL)

message(STATUS "${Color_Magenta}[=== 系统网络库检查 ===]${Color_Reset}")

# 检查网络相关库
enhanced_check_library_exists(nsl gethostbyname "" HAVE_LIBNSL)
enhanced_check_library_exists(socket socket "" HAVE_LIBSOCKET)
enhanced_check_library_exists(resolv inet_aton "" HAVE_LIBRESOLV)
enhanced_check_library_exists(bind __inet_aton "" HAVE_LIBBIND)

# 将找到的网络库添加到所需的库列表中
message(STATUS "${Color_Gray}[配置]${Color_Reset} 配置网络链接库...")

if(HAVE_LIBNSL)
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} nsl)
    SET(NETWORK_LIBRARIES ${NETWORK_LIBRARIES} nsl)
    message(STATUS "${Color_Cyan}[添加]${Color_Reset} nsl")
endif(HAVE_LIBNSL)
if(HAVE_LIBSOCKET)
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} socket)
    SET(NETWORK_LIBRARIES ${NETWORK_LIBRARIES} socket)
    message(STATUS "${Color_Cyan}[添加]${Color_Reset} socket")
endif(HAVE_LIBSOCKET)
if(HAVE_LIBRESOLV)
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} resolv)
    SET(NETWORK_LIBRARIES ${NETWORK_LIBRARIES} resolv)
    message(STATUS "${Color_Cyan}[添加]${Color_Reset} resolv")
endif(HAVE_LIBRESOLV)
if(HAVE_LIBBIND)
    # 该库用于 BeOS BONE 系统
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} bind)
    SET(NETWORK_LIBRARIES ${NETWORK_LIBRARIES} bind)
    message(STATUS "${Color_Cyan}[添加]${Color_Reset} bind (BeOS)")
endif(HAVE_LIBBIND)

# 对于 Win32 平台，无条件添加网络库链接 "ws2_32"
if(WIN32)
    SET(NETWORK_LIBRARIES ${NETWORK_LIBRARIES} ws2_32)
    message(STATUS "${Color_Cyan}[添加]${Color_Reset} ws2_32 (Win32)")
endif(WIN32)

message(STATUS "${Color_Magenta}[=== 系统头文件检查 ===]${Color_Reset}")

# 检查 POSIX 头文件
message(STATUS "${Color_Blue}[POSIX 头文件]${Color_Reset}")
enhanced_check_include_file_cxx(arpa/inet.h HAVE_ARPA_INET_H)
enhanced_check_include_file_cxx(dirent.h HAVE_DIRENT_H)
enhanced_check_include_file_cxx(grp.h HAVE_GRP_H)
enhanced_check_include_file_cxx(fcntl.h HAVE_FCNTL_H)
enhanced_check_include_file_cxx(netdb.h HAVE_NETDB_H)
enhanced_check_include_file_cxx(netinet/in.h HAVE_NETINET_IN_H)
enhanced_check_include_file_cxx(poll.h HAVE_POLL_H)
enhanced_check_include_file_cxx(pwd.h HAVE_PWD_H)
enhanced_check_include_file_cxx(sys/mman.h HAVE_SYS_MMAN_H)
enhanced_check_include_file_cxx(sys/resource.h HAVE_SYS_RESOURCE_H)
enhanced_check_include_file_cxx(sys/select.h HAVE_SYS_SELECT_H)
enhanced_check_include_file_cxx(sys/socket.h HAVE_SYS_SOCKET_H)
enhanced_check_include_file_cxx(sys/stat.h HAVE_SYS_STAT_H)
enhanced_check_include_file_cxx(sys/time.h HAVE_SYS_TIME_H)
enhanced_check_include_file_cxx(sys/types.h HAVE_SYS_TYPES_H)
enhanced_check_include_file_cxx(sys/utsname.h HAVE_SYS_UTSNAME_H)
enhanced_check_include_file_cxx(sys/wait.h HAVE_SYS_WAIT_H)
enhanced_check_include_file_cxx(termios.h HAVE_TERMIOS_H)
enhanced_check_include_file_cxx(unistd.h HAVE_UNISTD_H)

message(STATUS "${Color_Blue}[POSIX/SUS 可选头文件]${Color_Reset}")
enhanced_check_include_file_cxx(sys/timeb.h HAVE_SYS_TIMEB_H)

message(STATUS "${Color_Blue}[FreeBSD 头文件]${Color_Reset}")
enhanced_check_include_file_cxx(sys/event.h HAVE_SYS_EVENT_H)
enhanced_check_include_file_cxx(sys/param.h HAVE_SYS_PARAM_H)

message(STATUS "${Color_Blue}[BSD 头文件]${Color_Reset}")
enhanced_check_include_file_cxx(sys/file.h HAVE_SYS_FILE_H)

message(STATUS "${Color_Blue}[Linux 头文件]${Color_Reset}")
enhanced_check_include_file_cxx(sys/epoll.h HAVE_SYS_EPOLL_H)

message(STATUS "${Color_Blue}[Win32 头文件]${Color_Reset}")
enhanced_check_include_file_cxx(windows.h HAVE_WINDOWS_H)
enhanced_check_include_file_cxx(winsock2.h HAVE_WINSOCK2_H)
enhanced_check_include_file_cxx(ws2tcpip.h HAVE_WS2TCPIP_H)
enhanced_check_include_file_cxx(process.h HAVE_PROCESS_H)

message(STATUS "${Color_Blue}[其他头文件]${Color_Reset}")
enhanced_check_include_file_cxx(dir.h HAVE_DIR_H)
enhanced_check_include_file_cxx(direct.h HAVE_DIRECT_H)
enhanced_check_include_file_cxx(ndir.h HAVE_NDIR_H)
enhanced_check_include_file_cxx(sys/dir.h HAVE_SYS_DIR_H)
enhanced_check_include_file_cxx(sys/ndir.h HAVE_SYS_NDIR_H)
enhanced_check_include_file_cxx(sys/poll.h HAVE_SYS_POLL_H)

message(STATUS "${Color_Magenta}[=== 系统函数检查 ===]${Color_Reset}")

# 检查函数存在性
enhanced_check_function_exists(chdir HAVE_CHDIR)
enhanced_check_function_exists(epoll_create HAVE_EPOLL_CREATE)
enhanced_check_function_exists(fork HAVE_FORK)
enhanced_check_function_exists(ftime HAVE_FTIME)
enhanced_check_function_exists(getgid HAVE_GETGID)
enhanced_check_function_exists(getgrnam HAVE_GETGRNAM)
enhanced_check_function_exists(getlogin HAVE_GETLOGIN)
enhanced_check_function_exists(getopt HAVE_GETOPT)
enhanced_check_function_exists(getpid HAVE_GETPID)
enhanced_check_function_exists(getpwnam HAVE_GETPWNAME)
enhanced_check_function_exists(getrlimit HAVE_GETRLIMIT)
enhanced_check_function_exists(gettimeofday HAVE_GETTIMEOFDAY)
enhanced_check_function_exists(getuid HAVE_GETUID)
enhanced_check_function_exists(ioctl HAVE_IOCTL)
enhanced_check_function_exists(kqueue HAVE_KQUEUE)
enhanced_check_function_exists(_mkdir HAVE__MKDIR)
enhanced_check_function_exists(mkdir HAVE_MKDIR)
enhanced_check_function_exists(mmap HAVE_MMAP)
enhanced_check_function_exists(pipe HAVE_PIPE)
enhanced_check_function_exists(poll HAVE_POLL)
enhanced_check_function_exists(setitimer HAVE_SETITIMER)
enhanced_check_function_exists(setpgid HAVE_SETPGID)
enhanced_check_function_exists(setpgrp HAVE_SETPGRP)
enhanced_check_function_exists(setsid HAVE_SETSID)
enhanced_check_function_exists(setuid HAVE_SETUID)
enhanced_check_function_exists(sigaction HAVE_SIGACTION)
enhanced_check_function_exists(sigaddset HAVE_SIGADDSET)
enhanced_check_function_exists(sigprocmask HAVE_SIGPROCMASK)
enhanced_check_function_exists(strcasecmp HAVE_STRCASECMP)
enhanced_check_function_exists(strdup HAVE_STRDUP)
enhanced_check_function_exists(stricmp HAVE_STRICMP)
enhanced_check_function_exists(strncasecmp HAVE_STRNCASECMP)
enhanced_check_function_exists(strnicmp HAVE_STRNICMP)
enhanced_check_function_exists(strsep HAVE_STRSEP)
enhanced_check_function_exists(uname HAVE_UNAME)
enhanced_check_function_exists(wait HAVE_WAIT)
enhanced_check_function_exists(waitpid HAVE_WAITPID)

message(STATUS "${Color_Magenta}[=== 网络函数检查 ===]${Color_Reset}")

# 网络相关函数检查（Win32 平台特殊处理）
if(HAVE_WINSOCK2_H)
    message(STATUS "${Color_Green}[Win32]${Color_Reset} 检测到 WinSock2，自动启用相关网络函数")
    # 如果包含 WinSock2 头文件，则假定这些网络函数存在
    set(HAVE_GETHOSTNAME ON)
    set(HAVE_SELECT ON)
    set(HAVE_SOCKET ON)
    set(HAVE_RECV ON)
    set(HAVE_SEND ON)
    set(HAVE_RECVFROM ON)
    set(HAVE_SENDTO ON)
    set(HAVE_GETHOSTBYNAME ON)
    set(HAVE_GETSERVBYNAME ON)
else(HAVE_WINSOCK2_H)
    # 其他平台检查这些网络函数
    enhanced_check_function_exists(gethostname HAVE_GETHOSTNAME)
    enhanced_check_function_exists(select HAVE_SELECT)
    enhanced_check_function_exists(socket HAVE_SOCKET)
    enhanced_check_function_exists(recv HAVE_RECV)
    enhanced_check_function_exists(send HAVE_SEND)
    enhanced_check_function_exists(recvfrom HAVE_RECVFROM)
    enhanced_check_function_exists(sendto HAVE_SENDTO)
    enhanced_check_function_exists(gethostbyname HAVE_GETHOSTBYNAME)
    enhanced_check_function_exists(getservbyname HAVE_GETSERVBYNAME)
endif(HAVE_WINSOCK2_H)

message(STATUS "${Color_Magenta}[=== 其他配置 ===]${Color_Reset}")

# 检查 mkdir 函数的参数数量
message(STATUS "${Color_Gray}[检查]${Color_Reset} mkdir 参数数量...")
check_mkdir_args(MKDIR_TAKES_ONE_ARG)
if(MKDIR_TAKES_ONE_ARG)
    message(STATUS "${Color_Green}[结果]${Color_Reset} mkdir 使用 1 个参数")
else()
    message(STATUS "${Color_Green}[结果]${Color_Reset} mkdir 使用 2 个参数")
endif()

# 生成配置头文件
message(STATUS "${Color_Gray}[生成]${Color_Reset} config.h")
configure_file(config.h.cmake ${CMAKE_CURRENT_BINARY_DIR}/config.h)

message(STATUS "${Color_Green}[完成]${Color_Reset} 配置结束")
